name: build
on:
  push:
    branches:
      - master
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: show_python_version
        run: |
          python -V
          python3 -V

      - name: show_pip_version
        run: |
          pip -V
          pip3 -V

      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1.0.0
        with:
          command: "pipenv --version"
